title: TECHNET
description: خدمات تخصصی شبکه و امنیت
baseurl: "/TechNet" # اگر سایت در دامین اصلی است خالی بماند
url: "https://alimahdavi79.github.io"

# تنظیمات برای شناسایی بهتر فایل‌ها
markdown: kramdown

permalink: /blog/:title/  # آدرس مقالات به این شکل می‌شود
